name: "Test Workflow"

on: 
  push:
    branches:
      "**"

jobs:
  test_branch:
    name: Test Branch
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout repo
        uses: action/checkout@v3

      - name: Setup Python
        uses: action/setup-python@v3
        with:
          python-version: '3.10'

      - name: Instal dependencies
        uses: pip install -r requirements.txt

      - name: Create DB
        uses: DATABASE_URL=sqlite:///test.db python create_db.py

      - name: run test
        uses: DATABASE_URL=sqlite:///test.db pytest